### PR TITLE
Added user password change UIs

### PR DESCRIPTION
**Pull request by kwierchris**
image

### CODE REVIEW

**Comment by kwierchris** [comment]
The "Reset password" section is only seen by admins. It uses the auto generation function in auth and sends an email to the user's email address. This is the same stuff as auth is already doing it. But as I added new APIs to auth, the latest version of auth is required to test this functionality.

**Comment by kwierchris** [comment]
Where should I take these translations from?

**Comment by lasong** [comment]
I usually use google translate :D

**Comment by kwierchris** [comment]
Arne said, if we do not have the other translations, we leave them empty so they are english. I will not play Russian Roulett with our translations.

**Comment by lasong** [comment]
Haha okay

**Pull request merged**
